In [1]:
from poolparty.counter import Counter, CounterManager, synchronize_counters

with CounterManager() as mgr:
    A = Counter(5).named('A')
    B = Counter(3).named('B')
    ApB = (A+B).named('ApB')
    
    C = Counter(2).named('C')
    D = Counter(4).named('D')
    CxD = (C*D).named('CxD')
    
    E = synchronize_counters(ApB,CxD).named('E')

mgr.print_graph() 
mgr.test_iteration(E);

E [Synchronize, n=8]
├── ApB [Sum, n=8]
│   ├── A [Leaf, n=5]
│   └── B [Leaf, n=3]
└── CxD [Multiply, n=8]
    ├── C [Leaf, n=2]
    └── D [Leaf, n=4]

        A.state B.state  ApB.state  C.state  D.state  CxD.state  E.state
E.state
0             0    None          0        0        0          0        0
1             1    None          1        1        0          1        1
2             2    None          2        0        1          2        2
3             3    None          3        1        1          3        3
4             4    None          4        0        2          4        4
5          None       0          5        1        2          5        5
6          None       1          6        0        3          6        6
7          None       2          7        1        3          7        7

In [4]:
import poolparty as pp
L=5
with pp.Party() as party:
    A = pp.from_seqs(['A'*L,'C'*L, 'G'*L, 'T'*L], mode='sequential').named('A')
    B = pp.get_kmers(length=L, mode='hybrid', hybrid_mode_num_states=8).named('B')
    A2 = (2*A).named('A2')
    pp.sync([A2,B])
    C = pp.join([A2,B], spacer_str=' ').named('C')

party.print_graph(style='clean')
C.generate_seqs(num_complete_iterations=1, report_op_keys=False)

C (pool, n=8)
└── C.op [op=join, mode=fixed, n=1]
    ├── A2 (pool, n=8)
    │   └── A2.op [op=repeat, mode=sequential, n=2]
    │       └── A (pool, n=4)
    │           └── A.op [op=from_seqs, mode=sequential, n=4]
    └── B (pool, n=8)
        └── B.op [op=get_kmers, mode=hybrid, n=8]

,seq,C.seq,A2.seq,A.seq,B.seq,C.state,A.state,C.op.state,A2.op.state,A.op.state,B.op.state,id_6
0,AAAAA GTTGC,AAAAA GTTGC,AAAAA,AAAAA,GTTGC,0,0,0,0,0,0,0
1,CCCCC GTTCT,CCCCC GTTCT,CCCCC,CCCCC,GTTCT,1,1,0,0,1,1,1
2,GGGGG GTCCG,GGGGG GTCCG,GGGGG,GGGGG,GTCCG,2,2,0,0,2,2,2
3,TTTTT ATTGG,TTTTT ATTGG,TTTTT,TTTTT,ATTGG,3,3,0,0,3,3,3
4,AAAAA AAACA,AAAAA AAACA,AAAAA,AAAAA,AAACA,4,0,0,1,0,4,4
5,CCCCC TCCAA,CCCCC TCCAA,CCCCC,CCCCC,TCCAA,5,1,0,1,1,5,5
6,GGGGG CAACG,GGGGG CAACG,GGGGG,GGGGG,CAACG,6,2,0,1,2,6,6
7,TTTTT GCGGT,TTTTT GCGGT,TTTTT,TTTTT,GCGGT,7,3,0,1,3,7,7

In [ ]:
party.counter_manager.print_graph()