In [1]:
import poolparty as pp

In [2]:
# swapcase() swaps the case of all characters in a sequence
pool = pp.swapcase('ACGT').named('swapped')
pool.generate_library(num_seqs=1)

,seq,swapped.seq,op[0]:from_seq.key.seq,pool[0].seq,swapped.state,swapped.op.state,op[0]:from_seq.state,op[0]:from_seq.key.seq
0,acgt,acgt,ACGT,ACGT,0,0,0,ACGT

In [3]:
# replacement_scan with mark_changes=True highlights the insert by swapping its case
bg = 'AAAAAAAAAA'
ins = 'TTT'
pool = pp.replacement_scan(bg, ins, mark_changes=True, mode='sequential').named('scan')
pool.generate_library(num_cycles=1)

,seq,scan.seq,pool[7].seq,pool[6].seq,pool[5].seq,pool[4].seq,op[3]:from_seq.key.seq,pool[3].seq,op[2]:from_seq.key.seq,pool[2].seq,...,pool[2].state,scan.op.state,op[6]:seq_slice.state,op[5]:breakpoint_scan.state,op[4]:swapcase.state,op[3]:from_seq.state,op[2]:from_seq.state,op[5]:breakpoint_scan.key.breakpoints,op[3]:from_seq.key.seq,op[2]:from_seq.key.seq
0,tttAAAAAAA,tttAAAAAAA,AAAAAAA,AAAAAAAAAA,,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,0,0,0,0,"(0,)",TTT,AAAAAAAAAA
1,AtttAAAAAA,AtttAAAAAA,AAAAAA,AAAAAAAAA,A,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,1,0,0,0,"(1,)",TTT,AAAAAAAAAA
2,AAtttAAAAA,AAtttAAAAA,AAAAA,AAAAAAAA,AA,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,2,0,0,0,"(2,)",TTT,AAAAAAAAAA
3,AAAtttAAAA,AAAtttAAAA,AAAA,AAAAAAA,AAA,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,3,0,0,0,"(3,)",TTT,AAAAAAAAAA
4,AAAAtttAAA,AAAAtttAAA,AAA,AAAAAA,AAAA,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,4,0,0,0,"(4,)",TTT,AAAAAAAAAA
5,AAAAAtttAA,AAAAAtttAA,AA,AAAAA,AAAAA,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,5,0,0,0,"(5,)",TTT,AAAAAAAAAA
6,AAAAAAtttA,AAAAAAtttA,A,AAAA,AAAAAA,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,6,0,0,0,"(6,)",TTT,AAAAAAAAAA
7,AAAAAAAttt,AAAAAAAttt,,AAA,AAAAAAA,ttt,TTT,TTT,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,7,0,0,0,"(7,)",TTT,AAAAAAAAAA

In [4]:
# Party default for mark_changes can be set via set_default()
with pp.Party() as party:
    party.set_default('mark_changes', True)
    pool = pp.replacement_scan('AAAAAAAAAA', 'GGG', positions=[0], mode='sequential').named('result')
    df = pool.generate_library(num_cycles=1)
df

,seq,result.seq,pool[3].seq,pool[2].seq,pool[5].seq,pool[4].seq,op[1]:from_seq.key.seq,pool[1].seq,op[0]:from_seq.key.seq,pool[0].seq,...,pool[0].state,result.op.state,op[2]:swapcase.state,op[4]:seq_slice.state,op[3]:breakpoint_scan.state,op[1]:from_seq.state,op[0]:from_seq.state,op[3]:breakpoint_scan.key.breakpoints,op[1]:from_seq.key.seq,op[0]:from_seq.key.seq
0,gggAAAAAAA,gggAAAAAAA,,ggg,AAAAAAA,AAAAAAAAAA,GGG,GGG,AAAAAAAAAA,AAAAAAAAAA,...,0,0,0,0,0,0,0,"(0,)",GGG,AAAAAAAAAA