In [1]:
import poolparty as pp; pp.init()

# Demo: MarkerScanOp design card includes position_index, start, stop, length, region_name, region_content, strand, region
seq = "ACGTACGTACGT"

# Zero-length marker scan (start=stop, length=0, region_content='')
pool = pp.marker_scan(seq, marker='site', marker_length=0, mode='sequential')
df = pool.generate_library(report_design_cards=True)
display(df)

,seq,pool[1].seq,pool[0].seq,pool[1].state,pool[0].state,op[1]:marker_scan.state,op[0]:from_seq.state,op[1]:marker_scan.key.position_index,op[1]:marker_scan.key.start,op[1]:marker_scan.key.stop,op[1]:marker_scan.key.length,op[1]:marker_scan.key.region_name,op[1]:marker_scan.key.region_content,op[1]:marker_scan.key.strand,op[1]:marker_scan.key.region_seq
0,<site/>ACGTACGTACGT,<site/>ACGTACGTACGT,ACGTACGTACGT,0,0,0,0,0,0,0,0,site,,+,<site/>
1,A<site/>CGTACGTACGT,A<site/>CGTACGTACGT,ACGTACGTACGT,1,0,1,0,1,1,1,0,site,,+,<site/>
2,AC<site/>GTACGTACGT,AC<site/>GTACGTACGT,ACGTACGTACGT,2,0,2,0,2,2,2,0,site,,+,<site/>
3,ACG<site/>TACGTACGT,ACG<site/>TACGTACGT,ACGTACGTACGT,3,0,3,0,3,3,3,0,site,,+,<site/>
4,ACGT<site/>ACGTACGT,ACGT<site/>ACGTACGT,ACGTACGTACGT,4,0,4,0,4,4,4,0,site,,+,<site/>
5,ACGTA<site/>CGTACGT,ACGTA<site/>CGTACGT,ACGTACGTACGT,5,0,5,0,5,5,5,0,site,,+,<site/>
6,ACGTAC<site/>GTACGT,ACGTAC<site/>GTACGT,ACGTACGTACGT,6,0,6,0,6,6,6,0,site,,+,<site/>
7,ACGTACG<site/>TACGT,ACGTACG<site/>TACGT,ACGTACGTACGT,7,0,7,0,7,7,7,0,site,,+,<site/>
8,ACGTACGT<site/>ACGT,ACGTACGT<site/>ACGT,ACGTACGTACGT,8,0,8,0,8,8,8,0,site,,+,<site/>
9,ACGTACGTA<site/>CGT,ACGTACGTA<site/>CGT,ACGTACGTACGT,9,0,9,0,9,9,9,0,site,,+,<site/>
10,ACGTACGTAC<site/>GT,ACGTACGTAC<site/>GT,ACGTACGTACGT,10,0,10,0,10,10,10,0,site,,+,<site/>
11,ACGTACGTACG<site/>T,ACGTACGTACG<site/>T,ACGTACGTACGT,11,0,11,0,11,11,11,0,site,,+,<site/>
12,ACGTACGTACGT<site/>,ACGTACGTACGT<site/>,ACGTACGTACGT,12,0,12,0,12,12,12,0,site,,+,<site/>

In [2]:
# Region marker scan (start < stop, length=3, region_content shows the sequence)
pool2 = pp.marker_scan(seq, marker='region', marker_length=3, mode='sequential')
df = pool2.generate_library(report_design_cards=True)
display(df)

,seq,pool[3].seq,pool[2].seq,pool[3].state,pool[2].state,op[3]:marker_scan.state,op[2]:from_seq.state,op[3]:marker_scan.key.position_index,op[3]:marker_scan.key.start,op[3]:marker_scan.key.stop,op[3]:marker_scan.key.length,op[3]:marker_scan.key.region_name,op[3]:marker_scan.key.region_content,op[3]:marker_scan.key.strand,op[3]:marker_scan.key.region_seq
0,<region>ACG</region>TACGTACGT,<region>ACG</region>TACGTACGT,ACGTACGTACGT,0,0,0,0,0,0,3,3,region,ACG,+,<region>ACG</region>
1,A<region>CGT</region>ACGTACGT,A<region>CGT</region>ACGTACGT,ACGTACGTACGT,1,0,1,0,1,1,4,3,region,CGT,+,<region>CGT</region>
2,AC<region>GTA</region>CGTACGT,AC<region>GTA</region>CGTACGT,ACGTACGTACGT,2,0,2,0,2,2,5,3,region,GTA,+,<region>GTA</region>
3,ACG<region>TAC</region>GTACGT,ACG<region>TAC</region>GTACGT,ACGTACGTACGT,3,0,3,0,3,3,6,3,region,TAC,+,<region>TAC</region>
4,ACGT<region>ACG</region>TACGT,ACGT<region>ACG</region>TACGT,ACGTACGTACGT,4,0,4,0,4,4,7,3,region,ACG,+,<region>ACG</region>
5,ACGTA<region>CGT</region>ACGT,ACGTA<region>CGT</region>ACGT,ACGTACGTACGT,5,0,5,0,5,5,8,3,region,CGT,+,<region>CGT</region>
6,ACGTAC<region>GTA</region>CGT,ACGTAC<region>GTA</region>CGT,ACGTACGTACGT,6,0,6,0,6,6,9,3,region,GTA,+,<region>GTA</region>
7,ACGTACG<region>TAC</region>GT,ACGTACG<region>TAC</region>GT,ACGTACGTACGT,7,0,7,0,7,7,10,3,region,TAC,+,<region>TAC</region>
8,ACGTACGT<region>ACG</region>T,ACGTACGT<region>ACG</region>T,ACGTACGTACGT,8,0,8,0,8,8,11,3,region,ACG,+,<region>ACG</region>
9,ACGTACGTA<region>CGT</region>,ACGTACGTA<region>CGT</region>,ACGTACGTACGT,9,0,9,0,9,9,12,3,region,CGT,+,<region>CGT</region>